version: "3.9"

networks:
  nginxmanagerconecttelecom_default:
    external: true
  
services:
  frontend:
    restart: always
    container_name: FUNCIONARIO-NEXT-FRONTEND
    build: ./
    ports:
      - 3001
    networks:
      - nginxmanagerconecttelecom_default
  