"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation"; // Importe o useRouter corretamente
import "./globals.css";
import { Inter } from "next/font/google";
import imglogo from "../../public/img/logoportal.svg";
import Image from "next/image";
import useThemeSwitcher from "../app/useThemeSwitcher";
import { React, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Portal do Funcionario",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const currentPath = usePathname();
  const [mode, setMode] = useThemeSwitcher();
  const [isOpen, setIsOpen] = useState(false);

  const handleClick = () => {
    setIsOpen(!isOpen);
  };

  const currentYear = new Date().getFullYear();

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex  ">
          <div className="bg-neutral pt-5 flex flex-col col-span-1 items-center text-white w-sidebar">
            <div>
              <a
                className="btn  btn-ghost normal-case rounded-none w-full  text-md font-bold"
                href="/"
              >
                Portal do funcionario
                <figure className="mr-2">
                  <Image src={imglogo} alt="logo" width={40} height={80} />
                </figure>
              </a>
            </div>
            <button
              className={`rounded-md block  mb-1 mt-5 w-[25vh] py-2 px-4 shadow- ${
                currentPath === "/" ? "bg-gray-500 text-white" : "bg-neutral"
              } hover:bg-gray-500`}
              onClick={handleClick}
            >
              <Link href="/">Home</Link>
            </button>
            <button
              className={`rounded-md block mb-1  w-[25vh] py-2 px-4 ${
                currentPath === "/proporcional" ? "bg-gray-500" : "bg-neutral"
              } hover:bg-gray-500`}
            >
              <Link href="/proporcional">Proporcional</Link>
            </button>
            <button
              className={`rounded-md block mb-1  w-[25vh] py-2 px-4 ${
                currentPath === "/trocadeplano" ? "bg-gray-500" : "bg-neutral"
              } hover:bg-gray-500`}
            >
              <Link href="/trocadeplano">Troca de Plano</Link>
            </button>
            <button
              className={`rounded-md block mb-1  w-[25vh] py-2 px-4 ${
                currentPath === "/listramais" ? "bg-gray-500" : "bg-neutral"
              } hover:bg-gray-500`}
            >
              <Link href="/listramais">Lista de Ramais</Link>
            </button>
            <button
              className={`rounded-md block mb-1  w-[25vh] py-2 px-4 ${
                currentPath === "/ramais" ? "bg-gray-500" : "bg-neutral"
              } hover:bg-gray-500`}
            >
              <Link href="/ramais">Cadastrar Ramais</Link>
            </button>
            <button
              className={`rounded-md block mb-1  w-[25vh] py-2 px-4 ${
                currentPath === "http://10.0.9.20/"
                  ? "bg-gray-500"
                  : "bg-neutral"
              } hover:bg-gray-500`}
            >
              <Link href="http://10.0.9.20/" target="_blank">
                API Suporte
              </Link>
            </button>
            <button
              className={`rounded-md block mb-1  w-[25vh] py-2 px-4 ${
                currentPath === "https://conect-veiculos.netlify.app/login"
                  ? "bg-gray-500"
                  : "bg-neutral"
              } hover:bg-gray-500`}
            >
              <Link
                href="https://conect-veiculos.netlify.app/login"
                target="_blank"
              >
                Carros
              </Link>
            </button>
            <footer className="absolute bottom-0  text-white py-4 px-8 text-center">
              <Link
                className="text-sm"
                href={"https://dev-felipe-justus-portfolio.netlify.app"}
                target="_blank"
              >
                <p>Felipe Justus</p>
              </Link>
              <p className="text-sm">
                &copy; {currentYear} All Rights Reserved.
              </p>
            </footer>
          </div>

          <main className="flex flex-initial ml-10 pt-2 h-[100vh] rounded-tl-3xl   w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
